train<-read.csv("train.csv")
test<-read.csv("test.csv")
library(gbm)
library(dplyr)
category = train$Category
train = select(train, -Category)
end_trn = nrow(train)
all = rbind(train, test)
all = select(all, range1 , range2 , range3 , range4 , range5 , range6 , range7 , range8 , range9 , range10 , range11 , range12 , range13 , range14 , range15 , range16 , range17 , range18 , range19 , range20)
end=nrow(all)
Model = gbm.fit(x = all[1:end_trn,], y = category, distribution = "multinomial", n.trees = 5000, shrinkage = 0.01, interaction.depth = 3, n.minobsinnode = 10, nTrain = round(end_trn*0.8), verbose = TRUE)
#use perf to find best num of trees
gbm.perf(Model)
TestPredictions = predict(object = Model, newdata = all[(end_trn+1):end,], n.trees = gbm.perf(Model,plot.it = FALSE), type = "response")
TrainPredictions = predict(object = Model, newdata = all[1:end_trn,], n.trees = gbm.perf(Model,plot.it = FALSE), type = "response")
TestPredictions = round(TestPredictions)
TrainPredictions = round(TrainPredictions)
submission = data.frame(ID = 1:nrow(test), Category = TestPredictions)
write.csv(submission, file = "gbmResult.csv", row.names = FALSE)