train<-read.csv("train.csv")
test<-read.csv("test.csv")
library(gbm)
library(dplyr)
category = train$Style
train = select(train, -Style)
end_trn = nrow(train)
all = rbind(train, test)
end=nrow(all)
all = select(all, range0 , range1 , range2 , range3 , range4 , range5 , range6 , range7 , range8 , range9 , range10 , range11 , range12 , range13 , range14 , range15 , range16 , range17 , range18 , range19 , range20 , range21 , range22 , range23 , range24 , range25 , range26 , range27 , range28 , range29 , range30 , range41 , range42 , range43 , range44  , range45 , range46 , range47 , range48 , range49 , range50 , range51 , range52 , range53 , range54 , range55 , range56 , range57 , range58 , range59 , range60 , range61 , range62 , range63 , grayscale , contrast)
head(all)
Model = gbm.fit(x = all[1:end_trn,], y = category, distribution = "multinomial", n.trees = 5000, shrinkage = 0.01, interaction.depth = 3, n.minobsinnode = 10, nTrain = round(end_trn*0.75), verbose = TRUE)
#use perf to find best num of trees
gbm.perf(Model)
TestPredictions = predict(object = Model, newdata = all[(end_trn+1):end,], n.trees = gbm.perf(Model,plot.it = FALSE), type = "response")
TrainPredictions = predict(object = Model, newdata = all[1:end_trn,], n.trees = gbm.perf(Model,plot.it = FALSE), type = "response")
head(TrainPredictions,n=20)
head(category,n=20)
submission = data.frame(ID = test['imageID'], category = TestPredictions)
submission$max <- apply(submission[,2:15], 1, max)
write.csv(submission, file = "gbmResult.csv", row.names = FALSE)