train<-read.csv("train.csv")
test<-read.csv("test.csv")
library(randomForest)
set.seed(415)
fit <- randomForest(as.factor(Category) ~ range1 + range2 + range3 + range4 + range5 + range6 + range7 + range8 + range9 + range10 + range11 + range12 + range13 + range14 + range15 + range16 + range17 + range18 + range19 + range20, data=train, importance=TRUE, ntree=2000)
(VI_F=importance(fit))
varImpPlot(fit)
Prediction <- predict(fit, test)
submit <- data.frame(ID = test$imgID, Category = Prediction)
write.csv(submit, file = "firstforest.csv", row.names = FALSE)